name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build readme from apps.yml
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        shell: pwsh
        run: ./.github/Inoke-BuildReadme.ps1

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Github Actions] Build readme from apps.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
